import { useGameStore } from '../stores/gameStore';
import { usePlayerStore } from '../stores/playerStore';
import { useCardStore } from '../stores/cardStore';
import type { Enemy } from '../types';
import legacyCardsData from '../assets/data/legacyCards.json';
import type { LegacyCard } from '../types';
import { achievementManager } from './AchievementManager';
import { hapticsManager } from './HapticsManager';

// Victory callback to advance scenario
let victoryCallback: ((enemyId: string) => void) | null = null;

export const setVictoryCallback = (callback: (enemyId: string) => void) => {
  victoryCallback = callback;
};

// Card discovery on victory
export const discoverCardOnVictory = (enemyId: string) => {
  const cardStore = useCardStore.getState();

  // Map enemy IDs to potential card discoveries
  const cardRewards: Record<string, string[]> = {
    'event_001': ['card_004'], // Konnyaku monster -> Konnyaku card
  };

  const possibleCards = cardRewards[enemyId] || [];
  if (possibleCards.length > 0) {
    const cardId = possibleCards[Math.floor(Math.random() * possibleCards.length)];
    if (!cardStore.hasCard(cardId)) {
      cardStore.addCard(cardId);
      const allCards = legacyCardsData.cards as LegacyCard[];
      const card = allCards.find(c => c.id === cardId);
      if (card) {
        useGameStore.getState().addLog(`> 【カード発見】${card.name}を図鑑に登録しました！`, 'story');
      }
    }
  }
};

export class BattleSystem {
  private gameStore = useGameStore;
  private playerStore = usePlayerStore;
  private cardStore = useCardStore;

  private getActiveCards(): LegacyCard[] {
    const collectedCards = this.cardStore.getState().getAllCollectedCards();
    const allCards = legacyCardsData.cards as LegacyCard[];
    return allCards.filter(card => collectedCards.includes(card.id));
  }

  // private applyCardEffects() { ... } // Removed unused method


  startBattle(enemy: Enemy) {
    const playerState = this.playerStore.getState();

    // Apply battle start card effects (like Kusatsu Onsen)
    const activeCards = this.getActiveCards();
    activeCards.forEach(card => {
      if (card.effect.type === 'heal' && card.id === 'card_005') {
        const heal = card.effect.value || 0;
        const newHp = Math.min(playerState.maxHp, playerState.hp + heal);
        this.playerStore.setState({ hp: newHp });
        this.gameStore.getState().addLog(`> ${card.name}の効果: HPが${heal}回復した`, 'heal');
      }
    });

    this.gameStore.setState({
      battleState: {
        isActive: true,
        turn: 'player',
        enemy: { ...enemy },
        playerDice1: null,
        playerDice2: null,
        lastPlayerDamage: 0,
        lastEnemyDamage: 0,
      },
      currentMode: 'battle',
    });

    // Initial battle card should be generated by the UI/Scenario manager observing the state
    // We don't generate it here because we might want an initial "Encounter" message card first.
  }

  // Generate a card representing the current battle turn
  generateBattleCard(): any {
    const battleState = this.gameStore.getState().battleState;
    if (!battleState || !battleState.enemy) return null;

    const enemy = battleState.enemy;

    // Randomize enemy intent
    // 0: Attack (Aggressive)
    // 1: Vulnerable (Gap)
    // 2: Observing (Normal)
    const intentRoll = Math.random();
    let intent: 'attack' | 'vulnerable' | 'observing' = 'observing';
    let title = '';
    let description = '';
    let image = `/assets/enemies/enemy_${enemy.id.includes('daruma') ? 'daruma' : 'konnyaku'}.png`;

    if (intentRoll < 0.5) {
      intent = 'attack';
      title = `⚠️ ${enemy.name}が構えている！`;
      description = '殺気を感じる... 攻撃してくるぞ！\n(左: 防御 / 右: カウンター)';
    } else if (intentRoll < 0.8) {
      intent = 'vulnerable';
      title = `⚡ ${enemy.name}は隙だらけだ！`;
      description = '今なら大ダメージを与えられるチャンス！\n(左: 様子見 / 右: 攻撃)';
    } else {
      intent = 'observing';
      title = `👁️ ${enemy.name}はこちらを見ている`;
      description = '慎重に動いているようだ。\n(左: 牽制 / 右: 攻撃)';
    }

    return {
      id: `battle_${Date.now()}`,
      type: 'battle',
      title: title,
      description: description,
      image: image,
      meta: { intent },
      leftText: '🛡️ 防御/回避',
      rightText: '⚔️ 攻撃'
    };
  }

  processBattleSwipe(direction: 'left' | 'right', card: any) {
    const gameState = this.gameStore.getState();
    const battleState = gameState.battleState;
    if (!battleState || !battleState.enemy) return;

    const intent = card.meta?.intent || 'observing';
    const enemy = battleState.enemy;

    let playerDamage = 0;
    let enemyDamage = 0;
    let logMessage = '';

    // Logic Matrix
    if (direction === 'right') {
      // Player ATTACKS
      if (intent === 'attack') {
        // Clash! Both take damage
        playerDamage = Math.floor(enemy.attack * 0.8);
        enemyDamage = Math.floor(10 + Math.random() * 5);
        logMessage = `> 激突！相打ちになった！ (敵に${enemyDamage} / 自分${playerDamage})`;
      } else if (intent === 'vulnerable') {
        // Critical!
        enemyDamage = Math.floor(20 + Math.random() * 10);
        logMessage = `> クリティカル！隙を突いて大ダメージ！ (敵に${enemyDamage})`;
        gameState.triggerCriticalFlash();
      } else {
        // Normal hit
        enemyDamage = Math.floor(10 + Math.random() * 5);
        if (Math.random() > 0.7) {
          playerDamage = Math.floor(enemy.attack * 0.3);
          logMessage = `> 攻撃命中！しかし反撃を受けた (敵に${enemyDamage} / 自分${playerDamage})`;
        } else {
          logMessage = `> 攻撃命中！ (敵に${enemyDamage})`;
        }
      }
    } else {
      // Player DEFENDS / EVADES (Left)
      if (intent === 'attack') {
        // Perfect Dodge / Block
        logMessage = `> 攻撃を回避した！ノーダメージ。`;
      } else if (intent === 'vulnerable') {
        // Missed chance
        logMessage = `> 様子を見た... 絶好の機会を逃した。`;
      } else {
        // Stare down
        logMessage = `> 互いに睨み合っている... (HP微回復)`;
        const player = this.playerStore.getState();
        if (player.hp < player.maxHp) {
          this.playerStore.setState({ hp: Math.min(player.maxHp, player.hp + 5) });
        }
      }
    }

    // Apply Damage
    if (enemyDamage > 0) {
      const newEnemyHp = Math.max(0, enemy.hp - enemyDamage);
      this.gameStore.setState(state => ({
        battleState: { ...state.battleState!, enemy: { ...state.battleState!.enemy!, hp: newEnemyHp } }
      }));
    }

    if (playerDamage > 0) {
      const player = this.playerStore.getState();
      const newPlayerHp = Math.max(0, player.hp - playerDamage);
      this.playerStore.setState({ hp: newPlayerHp });
      hapticsManager.notificationError();
      gameState.triggerScreenShake();
    } else {
      hapticsManager.notification();
    }

    gameState.addLog(logMessage, 'battle');

    // Check Death
    const result = this.checkBattleEnd();
    if (result) {
      this.endBattle(result);
    }
  }

  checkBattleEnd(): 'victory' | 'defeat' | null {
    const gameState = this.gameStore.getState();
    const battleState = gameState.battleState;
    const playerState = this.playerStore.getState();

    if (!battleState?.isActive) {
      return null;
    }

    if (battleState.enemy && battleState.enemy.hp <= 0) {
      return 'victory';
    }

    if (playerState.hp <= 0) {
      return 'defeat';
    }

    return null;
  }

  endBattle(result: 'victory' | 'defeat') {
    const gameState = this.gameStore.getState();
    const battleState = gameState.battleState;
    const playerState = this.playerStore.getState();

    if (result === 'victory') {
      // Apply card effects that increase victory rewards
      const activeCards = this.getActiveCards();
      let rewardMultiplier = 1.0;

      activeCards.forEach(card => {
        if (card.effect.type === 'reward' && card.effect.value) {
          rewardMultiplier = Math.max(rewardMultiplier, card.effect.value);
          this.gameStore.getState().addLog(`> ${card.name}の効果: 報酬が${rewardMultiplier}倍になった!`, 'victory');
        }
      });

      // Tutorial Complete Logic
      if (!this.gameStore.getState().hasSeenTutorial) {
        this.gameStore.getState().setHasSeenTutorial(true);
        this.gameStore.getState().addLog('> システムが完全同期しました。全機能が解放されます。', 'story');
      }

      this.gameStore.getState().addLog('> 次のエリアへ進む...', 'info');

      // Discover card on victory
      if (battleState?.enemy?.id) {
        discoverCardOnVictory(battleState.enemy.id);
      }

      // Call victory callback to advance scenario
      if (victoryCallback && battleState?.enemy?.id) {
        victoryCallback(battleState.enemy.id);
      }

      // Phase 36: Track enemy defeats
      this.gameStore.getState().incrementStat('enemiesDefeated');
      achievementManager.onStatChange();

      // Phase 41: Grant exp and trigger result banner
      const expGained = Math.floor(30 + (battleState?.enemy?.hp || 0) * 0.5);
      const prevLevel = this.gameStore.getState().playerLevel;
      this.gameStore.getState().addExp(expGained);
      const newLevel = this.gameStore.getState().playerLevel;

      window.dispatchEvent(new CustomEvent('battleResult', {
        detail: {
          expGained,
          itemsGained: [],
          levelUp: newLevel > prevLevel ? { from: prevLevel, to: newLevel } : undefined
        }
      }));
    } else if (result === 'defeat') {
      // Set game over info
      const cause = battleState?.enemy?.name || '不明な敵';
      const lastDamage = battleState?.lastEnemyDamage || 0;
      this.gameStore.getState().setGameOverInfo({
        cause,
        location: playerState.location,
        lastDamage,
      });

      // Phase 36: Track deaths
      this.gameStore.getState().incrementStat('totalDeaths');
      achievementManager.onStatChange();
    }

    this.gameStore.setState({
      battleState: {
        ...battleState!,
        isActive: false,
      },
      currentMode: result === 'victory' ? 'exploration' : 'gameover',
      diceRollResult: null,
      diceRollResult2: null,
    });
  }

  getCurrentBattleState() {
    return this.gameStore.getState().battleState;
  }
}

